# Your Solution
version: '3'
services:
 # book-catalog Microservice
  book_catalog:
    image: $CONTAINER_REGISTRY.azurecr.io/book_catalog:$VERSION
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book_catalog
    environment:
      - PORT=8000
      - DATABASE_URL=postgresql://sit722part5_n6v2_user:7swYeCyduFOrAlSslBiL8I3Dnr0ATzcW@dpg-cru96p8gph6c73aenl3g-a.oregon-postgres.render.com/sit722part5_n6v2
    restart: "no"

  inventory_management:
    image: $CONTAINER_REGISTRY.azurecr.io/inventory_management:$VERSION
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory_management
    environment:
      - PORT=8001
      - DATABASE_URL=postgresql://sit722part5_n6v2_user:7swYeCyduFOrAlSslBiL8I3Dnr0ATzcW@dpg-cru96p8gph6c73aenl3g-a.oregon-postgres.render.com/sit722part5_n6v2
    restart: "no"